# Generated by Django 5.1 on 2024-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0044_alter_header_header_image_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_image_left',
            field=models.ImageField(default='', upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_image_right',
            field=models.ImageField(default='', upload_to='header/'),
        ),
    ]
