# Generated by Django 5.1 on 2024-11-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0045_alter_header_header_image_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
