# Generated by Django 5.1 on 2024-11-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0047_alter_header_header_image_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('Facebook', models.CharField(max_length=200)),
                ('Twitter', models.CharField(max_length=200)),
                ('Instagram', models.CharField(max_length=200)),
            ],
        ),
    ]
