# Generated by Django 5.1 on 2024-11-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0049_rename_phone_number_other_details_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_title', models.CharField(max_length=200)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_address', to='nep_app.other_details')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_email', to='nep_app.other_details')),
                ('Phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_phone_number', to='nep_app.other_details')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nep_app.header')),
            ],
        ),
    ]
